version: "3.8"
services:
  frontend:
    container_name: panel-frontend
    image: game-panel-frontend
    ports:
      - "5173:3000"
    links:
      - "backend"
    environment:
      - PUBLIC_BACKEND_URL=http://backend:8080
  backend:
    container_name: panel-backend
    image: game-panel-backend
    environment:
      - RUST_LOG=debug
