version: "3.8"
services:
  frontend:
    container_name: panel-frontend
    image: game-panel-frontend
    ports:
      - "3000:3000"
    links:
      - "backend"
  backend:
    container_name: panel-backend
    image: game-panel-backend
    environment:
      - RUST_LOG=debug
